# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wip',
                'doc_host': 'https://halkypi.github.io',
                'git_url': 'https://github.com/halkypi/wip',
                'lib_path': 'wip'},
  'syms': {'wip.core': {'wip.core.foo': ('core.html#foo', 'wip/core.py')}}}
